name: continuous deployment

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  deployment:
    uses: ArwynFr/ArwynFr/.github/workflows/pwsh-deployment.yaml@main
    with:
      manifest: ./ConventionalCommits/ConventionalCommits.psd1
      source: ./ConventionalCommits/
      tests: ./tests/Start-Tests.ps1
    secrets:
      CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
      PSGALLERY_APIKEY: ${{ secrets.PSGALLERY_APIKEY }}
